services:
    typesense:
        image: typesense/typesense:30.2
        command: --data-dir /data --api-key=xyz
        ports:
            - "8108:8108"
        volumes:
            - ./data:/data
        restart: unless-stopped
